---
journal: "Geochemistry, Geophysics, Geosystems"
classoption: "draft,linenumbers"
title: "RocMLMs: Predicting Rock Properties through Machine Learning Models"
authors:
  - name: "Buchanan Kerswell"
    affil: 1
  - name: "Nestor Cerpa"
    affil: 1
  - name: "Andréa Tommasi"
    affil: 1
  - name: "Marguerite Godard"
    affil: 1
  - name: "José Alberto Padrón-Navarta"
    affil: 2
affiliations:
  - number: 1
    name: "Géosciences Montpellier, Université de Montpellier & CNRS, Montpellier, France"
  - number: 2
    name: "Instituto Andaluz de Ciencias de la Tierra, CSIC–UGR, Granada, Spain"
corresponding_author:
  - name: "Buchanan Kerswell"
    email: "buchanan.kerswell@umontpellier.fr"
keypoints:  
  - "List up to three key points (at least one is required)"
  - "Key Points summarize the main points and conclusions of the article"
  - "Each must be 100 characters or less with no special characters or punctuation"
abstract: "Mineral phase transformations significantly alter the bulk density and elastic properties of mantle rocks and consequently have profound effects on mantle dynamics and seismic wave propagation. These changes in the physical properties of mantle rocks result from evolution in the equilibrium mineralogical composition, which can be predicted by the minimization of the  Gibbs Free Energy with respect to pressure (P), temperature (T), and chemical composition (X). Thus, numerical models that simulate mantle convection and/or probe the elastic structure of the Earth’s mantle must account for varying mineralogical compositions to be self-consistent. Yet coupling Gibbs Free Energy minimization (GFEM) approaches with numerical geodynamic models is currently intractable for high-resolution simulations because execution speeds of widely-used GFEM programs (~100–102 ms) are impractical in many cases. As an alternative, this study introduces machine learning models (RocMLMs) that have been trained to predict thermodynamically self-consistent rock properties at arbitrary PTX conditions between 1–28 GPa, 773–2273 K, and mantle compositions ranging from fertile (lherzolitic) to refractory (harzburgitic) end-members defined on a large dataset of published mantle compositions. RocMLMs are 101–103 times faster than GFEM calculations or GFEM-based look-up table approaches with equivalent accuracy. Depth profiles of RocMLMs predictions are nearly indistinguishable from reference models PREM and STW105, demonstrating good agreement between thermodynamic-based predictions of density, Vp, and Vs and geophysical observations. RocMLMs are therefore capable, for the first time, of emulating dynamic evolution of density, Vp, and Vs in high-resolution numerical geodynamic models."
plain_language_summary: "The mineralogical makeup of rocks within Earth’s mantle largely determines how the mantle flows over geologic time, and how it responds to seismic waves triggered by earthquakes, because mineral assemblages control important rock properties such as density and stiffness (elasticity). The mineralogy of mantle rocks is not constant, however. It changes depending on three factors: pressure, temperature, and the chemical composition of the rock. Thus, it is important for computer simulations of mantle convection to account for the evolution of rock mineralogy in time and space. Computer programs that can predict rock properties based on thermodynamic calculations of the most stable mineral assemblages are available, but these programs are generally too slow to be used in an iterative manner in high-resolution computer simulations of mantle convection. As an alternative approach, this study introduces machine learning models (RocMLMs) that have “learned” how to predict rock properties (density and elasticity) for a large range of mantle rock compositions and pressure-temperature conditions  by “training” on a large dataset of thermodynamic calculations. We demonstrate that RocMLMs can then predict rock properties up to 101–103 times faster than state-of-the-art methods. We tested RocMLM predictions against reference mantle models based on observations of seismic waves and found good agreement. RocMLMs are therefore capable of fast and highly-accurate predictions of changes in rock properties and can be implemented in high-resolution computer simulations of mantle convection."
output:
  bookdown::pdf_book:
    base_format: rticles::agu_article
    fig_caption: yes
    toc_depth: 3
    keep_tex: true
    citation_package: default
    latex_engine: pdflatex
    pandoc_args: [--csl=agu.csl]
bibliography: main.bib
header-includes: 
  - \usepackage{pdflscape}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \usepackage{longtable}
  - \usepackage{tabularx}
  - \usepackage{booktabs}
  - \usepackage{setspace}
  - \usepackage{caption}
  - \captionsetup[figure]{font={stretch=0.6}}
  - \usepackage{float}
  - \raggedbottom
  - \usepackage{soulutf8}
  - \usepackage[utf8]{inputenc}
  - \usepackage{amsmath}
  - \usepackage{amsfonts}
  - \usepackage{amssymb}
  - \DeclareUnicodeCharacter{02DA}{$^\circ$}
  - \DeclareUnicodeCharacter{2265}{$\geq$}
  - \DeclareUnicodeCharacter{2264}{$\leq$}
  - \DeclareUnicodeCharacter{177}{$\pm$}
  - \providecommand{\tightlist}{\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
  - \def\tightlist{}
  - \usepackage{hyperref}
---

```{r echo=FALSE}
options(tinytex.latexmk.emulation=F)
options(knitr.kable.NA='')
knitr::opts_chunk$set(echo=F, message=F, warning=F, fig.pos='htbp', out.extra='',
                      fig.align='center', out.width='100%')
```

```{r keypoints_check, echo=FALSE, results='asis', eval=TRUE}
if (any(nchar(rmarkdown::metadata$keypoints) > 100)) {
  cat("\\textcolor{red}{\\textbf{Warning}: keypoint(s)", 
      knitr::combine_words(which(nchar(rmarkdown::metadata$keypoints) > 100)), 
      "longer than 100 characters.}")
}
```

# Introduction

